# Simplified scenario for testing seasonal application rates
regions:
  - region_id: "test"
    region_name: "Test Region"

# Single segment with 10,000 population
population_segments:
  - segment_id: "test_segment"
    cohort_type: "test_cohort"
    region_id: "test"
    age_min: 0
    age_max: 100
    age_bracket_name: "all_ages"
    population_size: 10000

# Flow rates
flow_rates:
  # Set base application rate
  new_applications: 0.10  # This is the baseline rate
  
  # Set all other rates to zero to prevent state transitions
  new_enrollments: 1.0
  new_re_enrollment: 0.0
  new_first_claimants: 0.0
  new_re_enrollment_applications: 0.0

# Use our simple rollout
rollout_schedule_config: "simple_rollout"

# Disable random variation
distributions:
  new_applications_distribution:
    type: "normal"
    params:
      mean: 1.0
      stddev: 0.0