# Base configuration for OHB Simulation Model

# Simulation parameters
simulation:
  time_interval: "MONTHLY"
  fiscal_year_start_month: 4
  fiscal_year_start_day: 1

# States in the process flow
states:
  eligible_population:
    id: "eligible"
    name: "Eligible Population"
    reset_on_fiscal_year: false
  
  re_enrollment_eligible_population:
    id: "re_enrollment_eligible"
    name: "Re-enrollment Eligible Population"
    reset_on_fiscal_year: false
  
  applied_population:
    id: "applied"
    name: "Applied Population"
    reset_on_fiscal_year: false
  
  enrolled_inactive_population:
    id: "enrolled_inactive"
    name: "Enrolled Inactive Population"
    reset_on_fiscal_year: true
  
  active_claimant_population:
    id: "active_claimant"
    name: "Active Claimant Population"
    reset_on_fiscal_year: true
  
  non_eligible_population:
    id: "non_eligible"
    name: "Non-Eligible Population"
    reset_on_fiscal_year: false

# Flows between states
flows:
  new_applications:
    id: "new_applications"
    source: "eligible"
    target: "applied"
  
  new_re_enrollment_applications:
    id: "new_re_enrollment_applications"
    source: "re_enrollment_eligible"
    target: "applied"
  
  new_enrollments:
    id: "new_enrollments"
    source: "applied"
    target: "enrolled_inactive"
  
  new_re_enrollment:
    id: "new_re_enrollment"
    source: "applied"
    target: "enrolled_inactive"
  
  new_first_claimants:
    id: "new_first_claimants"
    source: "enrolled_inactive"
    target: "active_claimant"
  
  new_rejections:
    id: "new_rejections"
    source: "applied"
    target: "non_eligible"
    
  new_re_enrollment_rejections:
    id: "new_re_enrollment_rejections"
    source: "applied"
    target: "non_eligible"

# Default flow rates
flow_rates:
  # Application rates
  new_applications: 0.05         # 5% of eligible population applies each month
  new_re_enrollment_applications: 0.15  # 15% of re-enrollment eligible applies each month
  
  # Approval rates
  new_enrollments: 0.80          # 80% of applications are approved
  new_re_enrollment: 0.90        # 90% of re-enrollment applications are approved
  
  # Claimant rates
  new_first_claimants: 0.20      # 20% of inactive enrollees become first-time claimants each month

  # Cohort-specific rates
  new_applications_seniors_65plus: 0.08    # Higher application rate for seniors
  new_applications_pwd_all: 0.10           # Higher application rate for PWD
  new_applications_children_u18: 0.07      # Higher application rate for children

rollout_schedule_config: "rollout_schedule"

# Default rollout schedule, rolls out all cohorts together, do not modify this section
default_rollout_schedule:
  - phase_id: "default"
    cohort_id: "ALL"
    age_min: 0
    age_max: 120
    start_date: "2025-04-01"
    description: "Default rollout (all cohorts eligible)"

# Add this to your existing base_config.yaml
application_rates:
  test_cohort:
    base_rate: 0.10  # 10% base rate
    seasonal_factors:
      1: 2.0   # January: doubles the rate
      7: 0.5   # July: halves the rate

# Re-enrollment application rates by cohort
re_enrollment_rates:
  seniors:
    base_rate: 0.15
  pwd:
    base_rate: 0.18
  children:
    base_rate: 0.12
  adults:
    base_rate: 0.10

# Approval rates by application type and cohort
approval_rates:
  new_enrollments:
    seniors: 0.80
    pwd: 0.85
    children: 0.90
    adults: 0.75
  
  new_re_enrollment:
    seniors: 0.90
    pwd: 0.92
    children: 0.95
    adults: 0.85